pipeline:
  build:
    image: cogniteev/oracle-java
    commands: ./gradlew build test --no-daemon
  publish:
    image: cogniteev/oracle-java
    commands: 
    - ./gradlew publishversionedPublicationToParallelBlockRepository
    - ./gradlew publishLatestToParallelBlockRaw
    environment:
      - PUBLISH=yes
      - LATEST_BUILD=yes
    secrets: [SNAPSHOT_REPO, RELEASE_REPO, REPO_USERNAME, REPO_PASSWORD, RAW_UPLOAD_PATH]
    when:
      branch: master
      event: push
