name: Votifier
main: com.vexsoftware.votifier.NuVotifierBukkit
version: @app.version@
description: A plugin that gets notified when votes are made for the server on toplists.
      usage: /nvreload
      permission-message: You don't have permission to run this command.
      permission: nuvotifier.reload
   nvreload:
      description: This command reloads the NuVotifier Config
commands:
authors: [ParallelBlock, blakeman8192, Kramer, tuxed]